remote_theme: chrisrhymes/bulma-clean-theme

permalink: pretty

lang: en
title: CoGAPS
tagline: CoGAPS
description: >
  The website for CoGAPS (Coordinated Gene Association in Pattern Sets)
fixed_navbar: top
favicon: /images/FertigLabFavicon.png
footer_menu: footer_menu

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
